import torch
import time
from typing import Any, Dict
import ray
import tensorrt_llm

from llmperf.ray_llm_client import LLMClient
from llmperf.models import RequestConfig
from llmperf import common_metrics
from llmperf.utils import TensorRT

from tensorrt_llm.runtime import PYTHON_BINDINGS, ModelRunner

@ray.remote
class TensorRTLibClient(LLMClient):

    def __init__(self):
        self.tokenizer = None
        self.pad_id = None
        self.end_id = None
        self.runner = None

    def llm_request(self, request_config: RequestConfig) -> Dict[str, Any]:
        """Make a single completion request to a TesnorRT LLM Engine

        Returns:
            Metrics about the performance charateristics of the request.
            The text generated by the request to the LLM API.
            The request_config used to make the request. This is mainly for logging purposes.

        """
        model_name, model_version = TensorRT.read_model_name(
            request_config.engine_dir
        )

        if self.tokenizer is None or self.pad_id is None or self.end_id is None:
            self.tokenizer, self.pad_id, self.end_id = TensorRT.load_tokenizer(model_name=model_name)

        max_length = request_config.sampling_params["max_tokens"]

        if self.runner is None:
            runner_cls = ModelRunner
            runtime_rank = tensorrt_llm.mpi_rank()
            runner_kwargs = dict(
                engine_dir=request_config.engine_dir,
                lora_dir=None,
                rank=runtime_rank,
                debug_mode=False,
                lora_ckpt_source="hf",
                gpu_weights_percent=1,
                max_output_len=max_length,
            )
            self.runner = runner_cls.from_dir(**runner_kwargs)

        prompt = request_config.prompt
        prompt, prompt_len = prompt
        #TODO Add arg, default 5
        streaming_interval = request_config.streaming_interval

        tokens_received = 0
        ttft = 0
        first_token = None
        generated_text = ""
        output_ids = []
        metrics = {common_metrics.ERROR_CODE: None, common_metrics.ERROR_MSG: ""}

        try:
            input_ids = self.tokenizer.encode(
                prompt,
                truncation=True,
            )
            start_time = time.monotonic()
            with torch.no_grad():
                outputs = self.runner.generate(
                    batch_input_ids=[input_ids],
                    encoder_input_ids=None,
                    encoder_input_features=None,
                    encoder_output_lengths=None,
                    max_new_tokens=max_length,
                    max_attention_window_size=None,
                    sink_token_length=None,
                    end_id=self.end_id,
                    pad_id=self.pad_id,
                    temperature=1.0,
                    top_k=1,
                    top_p=0.0,
                    num_beams=1,
                    num_return_sequences=None,
                    length_penalty=1.0,
                    early_stopping=1,
                    repetition_penalty=1.0,
                    presence_penalty=0.0,
                    frequency_penalty=0.0,
                    stop_words_list=None,
                    bad_words_list=None,
                    output_cum_log_probs=False,
                    output_log_probs=False,
                    random_seed=0,
                    lora_uids=None,
                    prompt_table=None,
                    streaming=True,
                    output_sequence_lengths=True,
                    no_repeat_ngram_size=None,
                    return_dict=True,
                    medusa_choices=None,
                    return_all_generated_tokens=True,
                    input_token_extra_ids=None,
                )
                torch.cuda.synchronize()
            for curr_outputs in TensorRT.throttle_generator(outputs, streaming_interval):
                if runtime_rank == 0:
                    _output_ids = curr_outputs["output_ids"]
                    if first_token is None:
                        first_token = self.tokenizer.decode(_output_ids[0][-1], skip_special_tokens=True)
                        ttft = time.monotonic() - start_time
                    output_ids.append(_output_ids)
            generated_text = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
            total_request_time = time.monotonic() - start_time
            tokens_received = outputs.shape[1]
            output_throughput = tokens_received / total_request_time
        except Exception as e:
            metrics[common_metrics.ERROR_MSG] = str(e)
            print(f"Warning Or Error: {e}")

        metrics[common_metrics.INTER_TOKEN_LAT] = (
                                                          total_request_time - ttft
                                                  ) / tokens_received
        metrics[common_metrics.TTFT] = ttft
        metrics[common_metrics.E2E_LAT] = total_request_time
        metrics[common_metrics.REQ_OUTPUT_THROUGHPUT] = output_throughput
        metrics[common_metrics.NUM_TOTAL_TOKENS] = tokens_received + prompt_len
        metrics[common_metrics.NUM_OUTPUT_TOKENS] = tokens_received
        metrics[common_metrics.NUM_INPUT_TOKENS] = prompt_len

        return metrics, generated_text, request_config
